//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-04-01 16:37:24 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using zzbj.iBll;
using zzbj.models;

namespace zzbj.ibll
{
	/// <summary>
	/// IT_Cod_RiverOriginStandardBll
	/// </summary>	
	public interface  IT_Cod_RiverOriginStandardBll:IDependency<T_Cod_RiverOriginStandard>
    {


    }
}

