
using Autofac;
using zzbj.bll;
using zzbj.dal;
using zzbj.ibll;
using zzbj.idal;
using zzbj.models;
using zzbj.repository;
public class InjectModule
{
    /// <summary>
    /// 加载
    /// </summary>
    /// <param name="builder"></param>
	public static void  LoadInjectModule(ContainerBuilder builder)
	{
        builder.RegisterGeneric(typeof(Dal<>)).As(typeof(IDal<>)).InstancePerDependency();
        builder.RegisterGeneric(typeof(Repository<>)).As(typeof(IRepository<>)).InstancePerDependency();
		builder.RegisterType<personBll>().As<IpersonBll>();
        builder.RegisterType<customBll>().As<IcustomBll>();
		//------------------------------------------------------------------------------
		// <auto-generated>
		// 此代码由T4模板自动生成
		// 生成时间 2017-04-01 13:09:52 by ding
		// 对此文件的更改可能会导致不正确的行为，并且如果
		// 重新生成代码，这些更改将会丢失。
		// </auto-generated>
		//------------------------------------------------------------------------------
	    builder.RegisterType<bas_userBll>().As<Ibas_userBll>();

		//------------------------------------------------------------------------------
		// <auto-generated>
		// 此代码由T4模板自动生成
		// 生成时间 2017-04-01 13:09:52 by ding
		// 对此文件的更改可能会导致不正确的行为，并且如果
		// 重新生成代码，这些更改将会丢失。
		// </auto-generated>
		//------------------------------------------------------------------------------
	    builder.RegisterType<rel_menuactionsBll>().As<Irel_menuactionsBll>();

		//------------------------------------------------------------------------------
		// <auto-generated>
		// 此代码由T4模板自动生成
		// 生成时间 2017-04-01 13:09:52 by ding
		// 对此文件的更改可能会导致不正确的行为，并且如果
		// 重新生成代码，这些更改将会丢失。
		// </auto-generated>
		//------------------------------------------------------------------------------
	    builder.RegisterType<rel_rolemenusBll>().As<Irel_rolemenusBll>();

		//------------------------------------------------------------------------------
		// <auto-generated>
		// 此代码由T4模板自动生成
		// 生成时间 2017-04-01 13:09:52 by ding
		// 对此文件的更改可能会导致不正确的行为，并且如果
		// 重新生成代码，这些更改将会丢失。
		// </auto-generated>
		//------------------------------------------------------------------------------
	    builder.RegisterType<sys_actionBll>().As<Isys_actionBll>();

		//------------------------------------------------------------------------------
		// <auto-generated>
		// 此代码由T4模板自动生成
		// 生成时间 2017-04-01 13:09:52 by ding
		// 对此文件的更改可能会导致不正确的行为，并且如果
		// 重新生成代码，这些更改将会丢失。
		// </auto-generated>
		//------------------------------------------------------------------------------
	    builder.RegisterType<sys_menuBll>().As<Isys_menuBll>();

		//------------------------------------------------------------------------------
		// <auto-generated>
		// 此代码由T4模板自动生成
		// 生成时间 2017-04-01 13:09:52 by ding
		// 对此文件的更改可能会导致不正确的行为，并且如果
		// 重新生成代码，这些更改将会丢失。
		// </auto-generated>
		//------------------------------------------------------------------------------
	    builder.RegisterType<sys_roleBll>().As<Isys_roleBll>();

	}
}