//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-04-01 13:02:07 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class rel_rolemenus
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public string roleid { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string menuid { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime createdate { get; set; }
		   
    }
}

