//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-04-01 13:02:08 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class sys_role
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public string id { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string rowname { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime createtime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string remarks { get; set; }
		   
    }
}

