//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Bas_MaterialUseRecord
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public string UseID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string UsePerson { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime UseDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string UseDept { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int UseNum { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string UsePurpose { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string InventoryID { get; set; }
		   
    }
}

