//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Bas_MaterialPurchaseRecord
    {
        public string Record_ID { get; set; }
        public string PurchaseMaterialID { get; set; }
        public string PurchasePerson { get; set; }
        public string PurchaseDepart { get; set; }
        public Nullable<double> PurchaseNum { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<int> IsStatus { get; set; }
        public string Objection { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public Nullable<int> IsThrough { get; set; }
    }
}
