//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Bas_WaterItem
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public string WaterItemCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string WaterItemName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CharCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ChineseCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Unit { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal MaxValue { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal MinValue { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal LowestOut { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string WaySource { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int DayCount { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int MonthCount { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Remarks { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsStatus { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsShow { get; set; }
		   
    }
}

