//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Bas_Device
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public string DeviceCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string DeviceName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PointCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int DataTransWay { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int RunStatus { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int CommunicationType { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int OnlineStatus { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int PointType { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Remarks { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsStatus { get; set; }
		   
    }
}

