//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Bas_SeaWaterItem
    {
        public string SeaWaterItemCode { get; set; }
        public string SeaWaterItemame { get; set; }
        public string CharCode { get; set; }
        public string ChineseCode { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> MaxValue { get; set; }
        public Nullable<decimal> MinValue { get; set; }
        public string CountryCode { get; set; }
        public Nullable<decimal> LowestOut { get; set; }
        public string WaySource { get; set; }
        public Nullable<int> DayCount { get; set; }
        public Nullable<int> MonthCount { get; set; }
        public Nullable<int> PolluteID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> IsStatus { get; set; }
        public Nullable<int> IsShow { get; set; }
    }
}
