//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Bas_Module
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int MouduleID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int ApplicationID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MouduleName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int ParentID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsUse { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int Path { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int OrderID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string IcoPath { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MenuUrl { get; set; }
		
		/// <summary>
		/// 0含有1不含有
		/// </summary>		
		public int IsFuntion { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int MouduleType { get; set; }
		   
    }
}

