//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Bas_DeviceCalibratePoint
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public string RecordID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string RunTypeID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CurveID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CalibrateParamID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string TestValue { get; set; }
		   
    }
}

