//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Bas_MaterialPurchaseRecord
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public string Record_ID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PurchaseMaterialID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PurchasePerson { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PurchaseDepart { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public double PurchaseNum { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime PurchaseDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsStatus { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Objection { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Remarks { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime ConfirmDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsThrough { get; set; }
		   
    }
}

