//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Bas_DeviceInfo
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public string deviceID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string deviceNum { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string deviceName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string specType { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string leaveFactoryNum { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string measureArea { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string nicety { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime buyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string manufacturer { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string temperatureAsk { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string humidityAsk { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int DeviceStatus { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int isTab { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string deviceDoc { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string deviceDocType { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string depositPlace { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string calibrateUnit { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime checkDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime disuseDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string deviceTypeID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string DEPTID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal CalibrateCycle { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Custodian { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CalibrateCycleName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal CalibrateRemindDays { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int MaintainCycle { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MaintainCycleName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal MaintainRemindDays { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string remark { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string datafilepath { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string datafilesavepath { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string savedfilepath { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string capturemethodid { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsMaintain { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal BuyPrice { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int LinkID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int MonitorPK_ID { get; set; }
		   
    }
}

