//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Bas_GridInfo
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int GridCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string GridName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StaionCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int NoiseFunctionCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int SoundSourceCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal Latitude { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal Longitude { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int LinkID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int Num { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public double Long { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public double Wide { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsStatistics { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Remarks { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsStatus { get; set; }
		   
    }
}

