//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Bas_DrinkingWaterFactoryInfo
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int FactoryID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int DrinkingSourceID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string FactoryName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string FactoryLocation { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ServiceCity { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public double DesignQSL { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public double ActualQSL { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public double UsePersonsNum { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsStatue { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Remarks { get; set; }
		   
    }
}

