//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Bas_Materials
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public string MaterialID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MaterialName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MaterialTypeId { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public double StockLowerLimit { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public double StockUpperLimit { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal DueRemindDays { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Unit { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Remarks { get; set; }
		   
    }
}

