//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Bas_RiversInfo
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int RiversID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string RiverViewCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string RiversName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int WaterSystemID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int WaterSourceTypeID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public double Long { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public double Wide { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Function { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Remarks { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsStatus { get; set; }
		   
    }
}

