//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Bas_MaterialPurchase
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public string PurchaseMaterialID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MaterialID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MaterialModelID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string AppllyPerson { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ApplyDept { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Application { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string TechnologyRequire { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CheckRequire { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int Status { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime ApplyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime HopeDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime ReallyDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public double ApplyNumber { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public double ReallyNumber { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Unit { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ApplyFileName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid ExamineUserId { get; set; }
		   
    }
}

