//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Bas_DeviceExamineNotes
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int ExamineNotesId { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ApplyServiceCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid UserId { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid DEPTID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Content { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Result { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime ExamineTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime NextExamineTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Remarks { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsStatus { get; set; }
		   
    }
}

