//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Bas_DeviceCalibrateCurve
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public string CurveID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string AnalysePerson { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime Drawdate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime LoseDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal Slope { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal Intercept { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal RelatedCoefficient { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string standardcurve { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string deviceID { get; set; }
		   
    }
}

