//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Bas_MaterialInventory
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public string InventoryID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MaterialID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MaterialModelID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Provider { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string BatchNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime ExpirationDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string DepositPlace { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string DepositCondition { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Storeman { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal StorageNum { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal RemainingNum { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal Consistence { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Uncertainty { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string DilutionMultiple { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ProcessStatus { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string WarehouseId { get; set; }
		   
    }
}

