//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Bas_LakeVerticaPointlInfo
    {
        public string LakeVerticaCode { get; set; }
        public string CXCode { get; set; }
        public string LakeVerticaName { get; set; }
        public Nullable<int> LakeID { get; set; }
        public Nullable<int> WaterQualityID { get; set; }
        public string FunctionAreaCode { get; set; }
        public Nullable<decimal> Area { get; set; }
        public string StaionCode { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<int> LinkID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> IsStatus { get; set; }
        public Nullable<int> ControlLevelID { get; set; }
    }
}
