//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Bas_SectionPointInfo
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int RiversID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string DMCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal Area { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string SectionPointName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StaionCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal Longitude { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal Latitude { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int WaterQualityID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int LinkID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string SectionPointCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string FunctionAreaCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Remarks { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsStatus { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int ControlLevelID { get; set; }
		   
    }
}

