//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Bas_TrafficNoisePointInfo
    {
        public string TrafficNoisePointCode { get; set; }
        public string TrafficNoisePointName { get; set; }
        public string StaionCode { get; set; }
        public Nullable<double> Long { get; set; }
        public Nullable<double> Wide { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> CarFlowrate { get; set; }
        public Nullable<int> LinkID { get; set; }
        public Nullable<int> RoadCode { get; set; }
        public Nullable<int> SoundSourceCode { get; set; }
        public string BuildingWay { get; set; }
        public Nullable<int> LargeTrucks { get; set; }
        public Nullable<int> IsStatistics { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> IsStatus { get; set; }
    }
}
