//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Code_RiverQualityStandard
    {
        public int ID { get; set; }
        public string YearStart { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> MinValue { get; set; }
        public Nullable<decimal> LimitValue { get; set; }
        public Nullable<int> WaterLevel { get; set; }
        public Nullable<int> WaterType { get; set; }
    }
}
