//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Code_SeaWaterFunction
    {
        public string SeaWaterFunctionCode { get; set; }
        public string SeaWaterFunctionName { get; set; }
        public Nullable<int> WaterQualityID { get; set; }
        public string ApplyFunction { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<double> StandardArea { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> IsStatus { get; set; }
        public int PK_ID { get; set; }
        public string CountryCode { get; set; }
    }
}
