//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Code_GasStandardLimit
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int id { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string GasItemCode { get; set; }
		
		/// <summary>
		/// 枚举:0:年平均,1:24小时平均2:小时平均3:日最大一小时平均,4:季平均
		/// </summary>		
		public int TimeType { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int QualityLevel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal LimitValue { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StardandYear { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int Year { get; set; }
		   
    }
}

