//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Cod_GasOriginStandard
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int ID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ItemCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ItemName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal DayOne_WaterLevel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal DayTwo_WaterLevel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal DayThree_WaterLevel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal MonthOne_WaterLevel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal MonthTwo_WaterLevel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal MonthThree_WaterLevel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal QuarterlyOne_WaterLevel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal QuarterlyTwo_WaterLevel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal QuarterlyThree_WaterLevel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal YearOne_WaterLevel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal YearTwo_WaterLevel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal YearThree_WaterLevel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime InsertTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StandardYear { get; set; }
		   
    }
}

