//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Cod_StandardToLimit
    {
		
		/// <summary>
		/// 1是24小时滑日报动值（主要用于日报）  2是一小时平均（主要用于小时报表）
		/// </summary>		
		public int StandardLimitID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string GasItemCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal MaxValue { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal MinValue { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int Standard { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int UpLimit { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal ConfigValue { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsStatus { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int timeType { get; set; }
		   
    }
}

