//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Code_WaterItemLimit
    {
        public int PK_ID { get; set; }
        public Nullable<int> WaterQualityID { get; set; }
        public string WaterItemCode { get; set; }
        public Nullable<double> MinValue { get; set; }
        public Nullable<double> MaxValue { get; set; }
        public Nullable<int> IsStatus { get; set; }
        public Nullable<int> CYPD { get; set; }
        public string Flag { get; set; }
        public string UseYear { get; set; }
        public string StandardName { get; set; }
        public Nullable<int> OriginalID { get; set; }
    }
}
