//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Cod_SeaWaterOriginStandard
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int ID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StandardYear { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Itemcode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ItemName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal One_Standard { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal Two_Standard { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal Three_Standard { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal Four_Standard { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime InsertTime { get; set; }
		   
    }
}

