//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Cod_GasOriginStandard
    {
        public int ID { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> DayOne_WaterLevel { get; set; }
        public Nullable<decimal> DayTwo_WaterLevel { get; set; }
        public Nullable<decimal> DayThree_WaterLevel { get; set; }
        public Nullable<decimal> MonthOne_WaterLevel { get; set; }
        public Nullable<decimal> MonthTwo_WaterLevel { get; set; }
        public Nullable<decimal> MonthThree_WaterLevel { get; set; }
        public Nullable<decimal> QuarterlyOne_WaterLevel { get; set; }
        public Nullable<decimal> QuarterlyTwo_WaterLevel { get; set; }
        public Nullable<decimal> QuarterlyThree_WaterLevel { get; set; }
        public Nullable<decimal> YearOne_WaterLevel { get; set; }
        public Nullable<decimal> YearTwo_WaterLevel { get; set; }
        public Nullable<decimal> YearThree_WaterLevel { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public string StandardYear { get; set; }
    }
}
