//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Cod_SeaWaterOriginStandard
    {
        public int ID { get; set; }
        public string StandardYear { get; set; }
        public string Itemcode { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> One_Standard { get; set; }
        public Nullable<decimal> Two_Standard { get; set; }
        public Nullable<decimal> Three_Standard { get; set; }
        public Nullable<decimal> Four_Standard { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
    }
}
