//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Code_SeaWaterFunction
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public string SeaWaterFunctionCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string SeaWaterFunctionName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int WaterQualityID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ApplyFunction { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public double Area { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public double StandardArea { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Remarks { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsStatus { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int PK_ID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CountryCode { get; set; }
		   
    }
}

