//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Code_QualityLevel
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int QualityLevelID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string QualityLevelName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Color { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Status { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Affect { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Suggestion { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsStatus { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string RGB { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CMYK { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int MinValue { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int MaxValue { get; set; }
		   
    }
}

