//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Code_GasItemTypeRelevance
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int GasItemTypeRelevanceID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string GasItemCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int GasItemTypeID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsStatus { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Remarks { get; set; }
		   
    }
}

