//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Code_LakeQualityStandard
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int ID { get; set; }
		
		/// <summary>
		/// 标准年限
		/// </summary>		
		public string YearStart { get; set; }
		
		/// <summary>
		/// 因子Id
		/// </summary>		
		public string ItemCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal MinValue { get; set; }
		
		/// <summary>
		/// 上限值
		/// </summary>		
		public decimal LimitValue { get; set; }
		
		/// <summary>
		/// 水质类别
		/// </summary>		
		public int WaterLevel { get; set; }
		
		/// <summary>
		/// 水类型：1河流，2湖库
		/// </summary>		
		public int WaterType { get; set; }
		   
    }
}

