//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Cod_StandardToLimit
    {
        public int StandardLimitID { get; set; }
        public string GasItemCode { get; set; }
        public Nullable<decimal> MaxValue { get; set; }
        public Nullable<decimal> MinValue { get; set; }
        public Nullable<int> Standard { get; set; }
        public Nullable<int> UpLimit { get; set; }
        public Nullable<decimal> ConfigValue { get; set; }
        public Nullable<int> IsStatus { get; set; }
        public Nullable<int> timeType { get; set; }
    }
}
