//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Code_QualityLevel
    {
        public int QualityLevelID { get; set; }
        public string QualityLevelName { get; set; }
        public string Color { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Affect { get; set; }
        public string Suggestion { get; set; }
        public Nullable<int> IsStatus { get; set; }
        public string RGB { get; set; }
        public string CMYK { get; set; }
        public Nullable<int> MinValue { get; set; }
        public Nullable<int> MaxValue { get; set; }
    }
}
