//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Sys_Users
    {
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string RealName { get; set; }
        public string Email { get; set; }
        public Nullable<int> IsStatus { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Tel { get; set; }
        public string Photo { get; set; }
        public Nullable<int> IsExamine { get; set; }
        public Nullable<int> ExamineStep { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
