//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Sys_OperationId
    {
        public System.Guid OperationId { get; set; }
        public string OperationName { get; set; }
        public string StrikeEventName { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> IsStatus { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
