//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-05-19 18:20:46 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace zzbj.models
{	
	public partial class T_Sys_Users
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid UserId { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string UserName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PassWord { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string RealName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Email { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsStatus { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int Sex { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Tel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Photo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsExamine { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int ExamineStep { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate { get; set; }
		   
    }
}

