//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AQIReportData
    {
        public int ID { get; set; }
        public string Item1 { get; set; }
        public string PercentNum1 { get; set; }
        public string Item2 { get; set; }
        public string PercentNum2 { get; set; }
        public string Item3 { get; set; }
        public string PercentNum3 { get; set; }
        public string Item4 { get; set; }
        public string PercentNum4 { get; set; }
        public string Item5 { get; set; }
        public string PercentNum5 { get; set; }
        public string Item6 { get; set; }
        public string PercentNum6 { get; set; }
        public string GasPointCode { get; set; }
        public string AQIValue { get; set; }
        public string FirstItems { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string GasPointName { get; set; }
        public string Status { get; set; }
        public string RGB { get; set; }
        public string QualityLevelName { get; set; }
        public string RegionName { get; set; }
    }
}
