//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AQIDaySinglePoint
    {
        public int ID { get; set; }
        public int SO2Item1 { get; set; }
        public int COItem2 { get; set; }
        public int PM10Item3 { get; set; }
        public int O3Item4 { get; set; }
        public int PM2_5Item5 { get; set; }
        public int NO2Item6 { get; set; }
        public string GasPointName { get; set; }
        public string GasPointCode { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
