//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DrinkingWaterSourceInfo
    {
        public Nullable<int> DrinkingSourceProperty { get; set; }
        public string CheckTypeName { get; set; }
        public Nullable<int> DrinkingWaterTypeID { get; set; }
        public string Location { get; set; }
        public Nullable<int> WaterSystemID { get; set; }
        public int DrinkingSourceID { get; set; }
        public string DrinkingSourceName { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string WaterSystemName { get; set; }
        public string ControlLevelName { get; set; }
        public string DrinkingWaterTypeName { get; set; }
        public Nullable<int> IsStatus { get; set; }
    }
}
