//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GasMonitorYearResult
    {
        public int ID { get; set; }
        public string GasPointName { get; set; }
        public string GasItemName { get; set; }
        public decimal AvgResultCount { get; set; }
        public decimal MinValue { get; set; }
        public decimal MaxValue { get; set; }
        public decimal AvgValue { get; set; }
        public decimal UperNum { get; set; }
        public decimal UperRate { get; set; }
        public string UperBS { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string GasItemCode { get; set; }
        public string GasPointCode { get; set; }
    }
}
