//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GasItemTypeAndRealTimeData
    {
        public int ID { get; set; }
        public string GasPointCode { get; set; }
        public string GasItemCode { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<System.DateTime> MonitorTime { get; set; }
        public Nullable<int> DataType { get; set; }
        public Nullable<int> IsStatus { get; set; }
        public string GasItemName { get; set; }
        public int GasItemTypeID { get; set; }
        public string GasItemTypeName { get; set; }
        public string CharCode { get; set; }
        public string Unit { get; set; }
        public string GasPointName { get; set; }
        public Nullable<int> Monitor_Flag { get; set; }
    }
}
