//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LabMaterialStock
    {
        public string InventoryID { get; set; }
        public string MaterialID { get; set; }
        public string Provider { get; set; }
        public string BatchNo { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string DepositPlace { get; set; }
        public string Storeman { get; set; }
        public Nullable<decimal> StorageNum { get; set; }
        public Nullable<decimal> RemainingNum { get; set; }
        public string ProcessStatus { get; set; }
        public string WarehouseId { get; set; }
        public string WarehouseName { get; set; }
        public string MaterialName { get; set; }
        public Nullable<double> StockLowerLimit { get; set; }
        public Nullable<double> StockUpperLimit { get; set; }
        public Nullable<decimal> DueRemindDays { get; set; }
        public string Unit { get; set; }
        public string MaterialModelID { get; set; }
        public string MaterialModelName { get; set; }
        public string MaterialTypeName { get; set; }
        public string UserName { get; set; }
        public string RealName { get; set; }
    }
}
