//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LabMaterialApprovalShow
    {
        public string ExamineId { get; set; }
        public string PurchaseMaterialID { get; set; }
        public string MaterialModelName { get; set; }
        public string MaterialName { get; set; }
        public string ApplyName { get; set; }
        public string DEPTNAME { get; set; }
        public Nullable<double> ApplyNumber { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<int> IsThrough { get; set; }
        public Nullable<int> IsStatus { get; set; }
        public string Objection { get; set; }
        public string ExamineName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    }
}
