//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LabEquipmentRepairRequest
    {
        public string ApplyServiceCode { get; set; }
        public string deviceID { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> DEPTID { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public string Hitch { get; set; }
        public string ApplyFileName { get; set; }
        public Nullable<System.Guid> ExamineUserId { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> IsStatus { get; set; }
        public string deviceNum { get; set; }
        public string EquipmentDepart { get; set; }
        public string deviceName { get; set; }
        public string DEPTNAME { get; set; }
        public string ApplyName { get; set; }
        public string ApprovalName { get; set; }
        public string ApprovalName1 { get; set; }
        public string ApplyName1 { get; set; }
    }
}
