//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LabAblumMessage
    {
        public Nullable<System.Guid> PK_ID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> IsStatus { get; set; }
        public string ModelName { get; set; }
        public string Num { get; set; }
        public string Name { get; set; }
        public string UrlLink { get; set; }
        public string TitleName { get; set; }
    }
}
