//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LabEquipmentProject
    {
        public string DeviceExamineId { get; set; }
        public string ServiceCode { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> IsThrough { get; set; }
        public string Objection { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> IsStatus { get; set; }
        public string FileName { get; set; }
        public string deviceNum { get; set; }
        public string deviceName { get; set; }
        public string EquipmentDepart { get; set; }
        public string ApplyName { get; set; }
        public string ApprovalName1 { get; set; }
        public string ApplyName1 { get; set; }
        public Nullable<System.Guid> ApplyId { get; set; }
        public string Hitch { get; set; }
        public string WaitPeople { get; set; }
    }
}
