//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MaintainRecordInfo
    {
        public string PK_ID { get; set; }
        public string DeviceID { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<System.DateTime> MaintainDate { get; set; }
        public int IsMaintain { get; set; }
        public string deviceNum { get; set; }
        public string deviceName { get; set; }
        public string DEPTNAME { get; set; }
        public string deviceTypeName { get; set; }
        public Nullable<int> MaintainCycle { get; set; }
        public Nullable<decimal> MaintainRemindDays { get; set; }
        public string MaintainCycleName { get; set; }
        public Nullable<System.DateTime> DeadDate { get; set; }
        public string Remarks { get; set; }
        public string DEPTID { get; set; }
        public string deviceTypeID { get; set; }
        public string UserName { get; set; }
        public string RealName { get; set; }
        public Nullable<System.DateTime> disuseDate { get; set; }
    }
}
