//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_NoiseCityRangCountResult
    {
        public Nullable<System.Guid> PK_ID { get; set; }
        public string FuncitonNoisePointCode { get; set; }
        public string FuncitonNoisePointName { get; set; }
        public string SoundSourceName { get; set; }
        public Nullable<int> NoiseFunctionCode { get; set; }
        public Nullable<double> LEQA { get; set; }
        public Nullable<double> LEQS { get; set; }
        public Nullable<double> L10A { get; set; }
        public Nullable<double> L10S { get; set; }
        public Nullable<double> L50A { get; set; }
        public Nullable<double> L50S { get; set; }
        public Nullable<double> L90A { get; set; }
        public Nullable<double> L90S { get; set; }
        public Nullable<System.DateTime> MonitorTime { get; set; }
        public string NoiserFunctionName { get; set; }
    }
}
