//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_NoiseGridInfo
    {
        public int GridCode { get; set; }
        public string GridName { get; set; }
        public string StaionCode { get; set; }
        public Nullable<int> SoundSourceCode { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<int> LinkID { get; set; }
        public Nullable<int> Num { get; set; }
        public Nullable<double> Long { get; set; }
        public Nullable<double> Wide { get; set; }
        public Nullable<int> IsStatistics { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> IsStatus { get; set; }
        public string SoundSourceName { get; set; }
        public string StationName { get; set; }
        public string LinkName { get; set; }
        public string NoiserFunctionName { get; set; }
        public Nullable<int> NoiseFunctionCode { get; set; }
    }
}
