//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_NoiseRoadInfo
    {
        public int RoadCode { get; set; }
        public string RoadName { get; set; }
        public string CityCode { get; set; }
        public Nullable<double> Long { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<double> Wide { get; set; }
        public Nullable<int> IsStatus { get; set; }
        public string CityID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
