//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RiversInfo
    {
        public string WaterSystemName { get; set; }
        public string WaterSourceName { get; set; }
        public string RiversName { get; set; }
        public int RiversID { get; set; }
        public Nullable<int> WaterSystemID { get; set; }
        public Nullable<int> WaterSourceTypeID { get; set; }
        public Nullable<double> Long { get; set; }
        public Nullable<double> Wide { get; set; }
        public string Function { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> IsStatus { get; set; }
    }
}
