//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RiverSectionPointRegion
    {
        public string SectionPointCode { get; set; }
        public string SectionPointName { get; set; }
        public string StaionCode { get; set; }
        public string RegionCode { get; set; }
        public string RegionName { get; set; }
        public string ParentNode { get; set; }
    }
}
