//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SelectAQIReportContains24HourData
    {
        public decimal ID { get; set; }
        public decimal SO2Item1 { get; set; }
        public decimal SO2PercentNum1 { get; set; }
        public decimal COItem2 { get; set; }
        public decimal COPercentNum2 { get; set; }
        public decimal PM10Item3 { get; set; }
        public decimal PM10PercentNum3 { get; set; }
        public decimal O3Item4 { get; set; }
        public decimal O3HDPercentNum4 { get; set; }
        public decimal PM2_5Item5 { get; set; }
        public decimal PM2_5HDPercentNum5 { get; set; }
        public decimal NO2Item6 { get; set; }
        public decimal NO2PercentNum6 { get; set; }
        public decimal O3HDItem7 { get; set; }
        public decimal PM2_5HDItem8 { get; set; }
        public decimal AQI { get; set; }
        public string FirstPollutantNames { get; set; }
        public string AQILevel { get; set; }
        public string GasPointCode { get; set; }
        public string GasPointName { get; set; }
        public System.DateTime CurrentDate { get; set; }
    }
}
