//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_StationLinkRegion
    {
        public string StaionCode { get; set; }
        public string RegionName { get; set; }
        public string RegionCode { get; set; }
        public string StationName { get; set; }
        public Nullable<int> LinkID { get; set; }
        public string LinkName { get; set; }
        public string Phone { get; set; }
        public string CheckTypeName { get; set; }
        public Nullable<int> CheckTypeID { get; set; }
        public string FunctionAreaCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> IsStatus { get; set; }
    }
}
