//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UserRightsView
    {
        public string MouduleName { get; set; }
        public int MouduleID { get; set; }
        public string RoleName { get; set; }
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public System.Guid RoleId { get; set; }
        public System.Guid OperationId { get; set; }
        public string OperationName { get; set; }
        public string MenuUrl { get; set; }
        public string StrikeEventName { get; set; }
        public Nullable<int> ApplicationID { get; set; }
    }
}
