//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zzbj.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WaterSectionInfo
    {
        public Nullable<decimal> Area { get; set; }
        public string SectionPointName { get; set; }
        public string StaionCode { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<int> WaterQualityID { get; set; }
        public Nullable<int> LinkID { get; set; }
        public string SectionPointCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> IsStatus { get; set; }
        public Nullable<int> ControlLevelID { get; set; }
        public string RiversName { get; set; }
        public string WaterSourceName { get; set; }
        public string WaterSystemName { get; set; }
        public Nullable<int> WaterSystemID { get; set; }
        public Nullable<int> WaterSourceTypeID { get; set; }
        public string StationName { get; set; }
        public string ControlLevelName { get; set; }
        public string LinkName { get; set; }
        public string RegionName { get; set; }
        public string RegionCode { get; set; }
        public int RiversID { get; set; }
        public string WaterQualityName { get; set; }
        public string DMCode { get; set; }
    }
}
