//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-04-01 13:04:52 by ding
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using zzbj.ibll;
using zzbj.models;
using zzbj.repository;

namespace zzbj.bll
{
	/// <summary>
	/// Ibas_userBll
	/// </summary>	
	public  class  bas_userBll:Ibas_userBll
    {
	    private readonly IRepository<bas_user> _repository;
        public bas_userBll(IRepository<bas_user> repository)
        {
            _repository = repository;
        }

        public void Insert(bas_user p)
        {
            _repository.Insert(p);
        }

        public void Update(bas_user p)
        {
            _repository.Update(p);
        }

        public void Delete(bas_user p)
        {
            _repository.Delete(p);
        }

    }
}

